
"""
Command line tool that loads the current library from an emulator, then
serializes it to disk. This has two purposes:
New animations get sent from Aseprite to the emulator, then they can be
written to file with this script. This file can then be loaded from the
emulator.

In many games, hooks need to get rewired because their graphics were
changed. This script can then save the new hooks to a file which can be
loaded by the emulator later on.
"""

import argparse
from collections import defaultdict
import re
import sys

try:
    import ramanimator as ra
except ImportError:
    print("Could not import the ramanimator python package. Follow the instructions online to install it.")
    exit(1)

def format_hook_file(slots, hooks, headless=False):
    """
    headless: Only prints the hook data. This is useful for games for
    which there is extra functionality implemented that cannot be
    serialized. In that case, the user will need to attach the lines
    printed here to the end of a hook file obtained elsewhere.
    """
    tmpl = """
--[[
This file is machine generated by tools/save-library.py
--]]

local base64 = require("base64")
local raslots = require("ramanimator/slot")
local rahooks = require("ramanimator/hook")

local slots = {
__SLOTDATA
}

local hooks = {
__HOOKDATA
}

return {slots, hooks}
"""
    
    slot_data = []
    slot_handles = {} # Slot name to its handle in the slots list.

    for name, slot in slots.items():
        slot = defaultdict(lambda: None, slot)

        if isinstance(slot.get("extras", None), list):
            slot["extras"] = {}

        handle = slot.get("extras", {}).get("internalName", None)
        if handle is None:
            handle = re.sub(r'[^a-zA-Z0-9_]', '', name)

        slot_handles[name] = handle

        if slot["kind"] == "tile":
            line = f'\t{handle}=raslots.TileSlot:new("{name}", 0x{slot["address"]:x}, {slot["width"]}, {slot["height"]}, {slot["layout"]}, {slot["order"]}, {ra.to_lua(slot["subSlots"])}, {ra.to_lua(slot["extras"])})'
            slot_data.append(line)

        elif slot["kind"] == "sprite":
            line = f'\t{handle}=raslots.SpriteSlot:new("{name}", {slot["width"]}, {slot["height"]}, {slot["layout"]}, {slot["order"]}, {ra.to_lua(slot["subSlots"])}, {ra.to_lua(slot["extras"])})'
            slot_data.append(line)

        else:
            raise Exception(f"Trying to write a slot of kind {slot["kind"]}, but those should not reach here.")

    slot_data = ",\n".join(slot_data)

    hook_data = []
    # First,  remove the ones dynamically generated as siblings.
    for name, hook in hooks.items():
        palettes = hook.get("palettes", None)
        if palettes is not None:
            palettes = [ra.pack_palette(pal) for pal in palettes]

        extras = hook.get("extras", None)

        if extras is not None and len(extras) > 0:
            for key, val in extras.items():
                if key == "twinTriggers":
                    new_list = []
                    for trigger in val:
                        trigger = ra.LuaToken(f'base64.decode("{trigger}")')
                        new_list.append(trigger)

                    extras[key] = new_list

        line = f'\t{name}=rahooks.Hook:new("{name}", slots.{slot_handles[hook["slotName"]]}, {ra.to_lua(hook.get("playerClass", None))}, base64.decode("{hook["trigger"]}"), {ra.to_lua(palettes)}, {ra.to_lua(extras)})'
        hook_data.append(line)

    hook_data = ",\n".join(hook_data) + ","

    if headless:
        return hook_data

    return tmpl.replace("__SLOTDATA", slot_data).replace("__HOOKDATA", hook_data)

def main():
    parser = argparse.ArgumentParser(
        description="Script to write a RAManimator library from the running emulator to files."
    )

    parser.add_argument(
        "-H", "--hooks",
        action="store",
        nargs="?",
        const=True,
        default="hooks.lua",
        help="Name of the file to which hooks will get exported. Default: 'hooks.lua'"
    )

    parser.add_argument(
        "-a", "--animations",
        action="store",
        default="anims.lua",
        help="Name of the file to which animations get exported. Default: 'anims.lua'"
    )

    parser.add_argument(
        "-c", "--config",
        action="store",
        default="game-config.lua",
        help="Name of the file to which the game configuration gets written. Default: 'game-config.lua'"
    )

    group = parser.add_mutually_exclusive_group()
    group.add_argument('--filter-updated', dest='filter', action='store_true', help='Handle only updated data')
    group.add_argument('--no-filter-updated', dest='filter', action='store_false', help='Handle all data')
    parser.set_defaults(filter=None)

    parser.add_argument(
        "--host",
        action="store",
        default="localhost",
        help="IP of the server on the emulator. Printed when the server is started."
    )

    parser.add_argument(
        "--port",
        action="store",
        default="8446",
        help="Port of the server on the emulator. Printed when the server is started."
    )

    args = parser.parse_args()

    filter_updated = args.filter

    try:
        with ra.Emuserver(ip=args.host, port=args.port) as server:
            library = server.send_command("getLibrary", {"filterUpdated": filter_updated})

            try:
                is_pokemon = library["extras"].get("isPkmnLib", False)
            except:
                is_pokemon = False

            if filter_updated is None:
                filter_updated = is_pokemon

            # Filter again in case we filter because this is a Pokemon
            # game and it wasn't explicitly set.
            hooks = [info for info in library["hooks"] if not info.get("isSibling", False) and not (filter_updated and not info.get("updated", False))]

            print(f"Loading {len(hooks)} hooks from the emulator, this can take a few seconds.")

            hooks = {info["name"]: server.send_command("getHook", {"name": info["name"], "includeSyntheticPalettes": True}) for info in hooks}

            if filter_updated:
                # Only animations that aren't automatically generated
                anims = [anim for anim in library["animations"] if anim.get("updated", False) and not anim.get("isSibling", False)]
            else:
                # Only manual updates are earmarked.
                anims = [anim for anim in library["animations"] if not anim.get("isSibling", False)]

            print(f"Loading {len(anims)} animations from the emulator, this can take a minute.")

            animations = {}

            for anim in anims:
                name = anim["name"]
                answer = server.send_command("getAnimation", {"name": name})
                if answer["status"] == "success":
                    animations[name] = answer["animation"]
                else:
                    print(answer)

            anims = animations

    except ConnectionRefusedError:
        print("Server refused connection. Ensure the server is running on the emulator and provide the IP and port printed on its startup if that is the case.")
        exit(2)

    exitcode = 0
    # Write slots and hooks
    hook_file = format_hook_file(library["slots"], hooks, headless=filter_updated)
    try:
        with open(args.hooks, "w") as out:
            if filter_updated:
                hook_text = f"""
-- Copy these to the end of the hook list in a copy of the base game's hook file:
{hook_file}
"""
                out.write(hook_text)
            else:
                out.write(hook_file)
    except IOError as err:
        sys.stderr.write(f"Error writing hooks file '{args.hooks}': {err}\n")
        exitcode += 4

    try:
        ra.save_animations(args.animations, anims)
    except IOError as err:
        sys.stderr.write(f"Error writing animations to file '{args.animations}': {err}\n")
        exitcode += 8

    animfile = args.animations

    if animfile.endswith(".lua"):
        animfile = animfile[:-4]

    if filter_updated:
        print(f"""
    Add a line like the following, with the correct path, to the end of the animations in your setup:
            anims[#anims + 1] = (require("myfiles/{animfile}"))
    """)
    else:
        print("If these are your first hook and animation files, copy them into [the scripts directory]/myfiles, then change their names in the game's setup. If you are just updating the files, just overwrite the old ones.")
    
    sys.exit(exitcode)

if __name__ == '__main__':
    main()
